export const storeActionTypes = {
  USER_MODES: {
    MANAGER: "manager",
    HR: "hr",
    RECRUITER: "recruiter",
  },
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  REQUEST_TYPES: {
    REQUEST_VACANCY: "REQUEST_VACANCY",
    ASSEMBLE_VACANCY: "ASSEMBLE_VACANCY",
    RE_OPEN_VACANCY: "RE_OPEN_VACANCY",
  },
  REQUEST_ACTIONS: {
    SEND_REQUEST_VACANCY: "SEND_REQUEST_VACANCY",
    SEND_REQUEST_VACANCY_AS_DRAFT: "SEND_REQUEST_VACANCY_AS_DRAFT",
    SEND_REQUEST_VACANCY_UPDATE: "SEND_REQUEST_VACANCY_UPDATE",
    GET_VACANCY_BOARD_DATA: "GET_VACANCY_BOARD_DATA",
    LOAD_NEXT_STEP: "LOAD_NEXT_STEP",
    LOAD_PREV_STEP: "LOAD_PREV_STEP",
  },
  STATUS_TYPES: {
    REQUESTDRAFT: 1,
    REQUESTED: 2,
    DRAFT: 3,
    INPROGRESS: 4,
    PAUSED: 5,
    DATEEXPIRED: 6,
    CANCELED: 7,
    CLOSED: 8,
  },
};
