export const CandidateActionTypes = {
  REQUEST_TYPES: {
    RELOAD_CANDIDATES_DATA: "RELOAD_CANDIDATES_DATA",
    CLOSE_CANDIDATE_MODAL: "CLOSE_CANDIDATE_MODAL",
  },
  REQUEST_ACTIONS: {
    SEND_REQUEST_CANDIDATE: "SEND_REQUEST_CANDIDATE",
    SAVE_REQUEST_AND_CLOSE: "SAVE_REQUEST_AND_CLOSE",
    LOAD_NEXT_STEP: "LOAD_NEXT_STEP",
    LOAD_PREV_STEP: "LOAD_PREV_STEP",
  },
};
